services:
  frame-up-order-app:
    image: ghcr.io/team-one-pos-tech/frameup-order-service:latest
    container_name: frame-up-order-app
    restart: always
    ports:
      - "5688:8080"
    networks:
      - frame-up-network
    depends_on:
      rabbitmq:
        condition: service_healthy 
      logbee.frontend.dev:
        condition: service_started

  frame-up-process-app:
    image: ghcr.io/team-one-pos-tech/frameup-process-service:latest
    container_name: frame-up-process-app
    restart: always
    ports:
      - "5888:8080"
    networks:
      - frame-up-network
    depends_on:
      rabbitmq:
        condition: service_healthy 
      
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    restart: always
    ports:
       - "5672:5672"
       - "15672:15672"
    networks:
       - frame-up-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 5

  frame-up-db:
    image: postgres:latest
    container_name: frame-up-db
    restart: always
    ports:
      - "5432:5432"
    networks:
      - frame-up-network
    volumes:
      - frame-up-db:/var/lib/postgresql/data

  logbee.backend.dev:
    image: catalingavan/logbee.backend:1.3.0
    container_name: logbee.backend.dev
    restart: unless-stopped
    volumes:
      - ./backend.appsettings.json:/app/appsettings.json
      - ./backend.logbee.json:/app/Configuration/logBee.json
    ports:
      - "44088:80"
    links:
      - "mongodb"
    networks:
      - frame-up-network

  logbee.frontend.dev:
    image: catalingavan/logbee.frontend:1.3.0
    container_name: logbee.frontend.dev
    restart: unless-stopped
    volumes:
      - ./frontend.appsettings.json:/app/appsettings.json
      - ./frontend.logbee.json:/app/Configuration/logBee.json
    ports:
      - "44080:80"
    links:
      - "logbee.backend.dev"
    networks:
      - frame-up-network

  mongodb:
    image: mongo:6.0.4
    container_name: logbee.mongodb.dev
    restart: unless-stopped
    ports:
      - "27017"
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    networks:
      - frame-up-network

  identity-app:
    image: ghcr.io/team-one-pos-tech/identity-service:latest
    container_name: identity-app
    restart: always
    networks:
      - frame-up-network
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "5488:8080"

volumes:
  frame-up-db:
  mongo-data:
  mongo-config:

networks:
  frame-up-network:
    driver: bridge
  default:
    name: logbee-net
    driver_opts:
      com.docker.network.driver.mtu: 1380